<a href="https://colab.research.google.com/github/varshithav-nri/Introduction-to-numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy - Numeric Python - Most powerful package or library to manipulate numbers

# Dimensions
#A - 1D array
#[A,B] // |A
#          B| - 2D array - Row//column
#3D
#Array - Storing, Manipulating similar data types - Convinient and faster

# Numpy-memory efficiency, supports multidimensional arrays
#speed(numpy operations)> speed(list operations)
#size(numpy operations) < size(list operations)
#Memory Optimization(numpy) > Memory Optimization(list Operations)

In [ ]:
#pip install numpy // pip3 install numpy

In [ ]:
import numpy as np

In [ ]:
#create numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
#2D  array-Matrix
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating arrey with default vaalues
#creating matrix with all value elments as One

allOnes = np.ones((2,3))
print(allOnes)
#creating matrix with all value elments as Zero

allZeros = np.zeros((2,3))
print(allZeros)
#creating matrix with all value elments as constents

allConstant = np.full((2,3),6)
print(allConstant)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
#crete an identity matrix
identity = np.eye(4)
print(identity)
#I.M = M
#identity bmatrix
#For all A belongs to R M*N
#Aij - 0 & Aii - 1

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# creating Random matrices
# with 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

rand2 = np.random.randint(10,20, (3,3))
print(rand2)

[[0.09724321 0.55812719 0.50200397]
 [0.77538276 0.87964867 0.23095357]
 [0.26152685 0.0555797  0.06357398]]
[[11 13 11]
 [14 10 15]
 [13 10 12]]


In [ ]:
# Array Properties
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

#shape,size,data type,dimensions of array
print(f'\nThe shape of the array is{arr.shape}')
print(f'The size of the array is {arr.size}')
print(f'The data type of the array is {arr.dtype}')
print(f'The dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [5 6 7 8]]

The shape of the array is(2, 4)
The size of the array is 8
The data type of the array is int64
The dimension of the array is 2


In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>

In [ ]:
# Indexing and slicing
#Access the elements in 1D array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])
#slicing the elements
print(arr[1:3])

# access element in 2D array
arr2 = np.array([[1,2,3],[5,6,7]])
print(arr2)
print(arr2[0,1])

print(arr2[1,:])
print(arr2[:,2])

[1 2 3 4]
4
[2 3]
[[1 2 3]
 [5 6 7]]
2
[5 6 7]
[3 7]


In [ ]:
#l1=[]
#[l1.append] for _ in range(10):
    #print(_)
l1=np.arange(10,-10,-2)
print(l1)

[10  8  6  4  2  0 -2 -4 -6 -8]


In [ ]:
#mathematical operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'sum of a and b is {a+b}')
print(a-b)
print(a*b)
print(a/b)

sum of a and b is [5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
#matrix multiplication (#rows = columns)
b1 = np.array([[1,2,3],[3,4,5]])
b2 = np.array([[5,6],[7,8],[1,2]])
print(b1)
print(b2)
c = np.dot(b1,b2)
d = np.dot(b2,b1) #b1*b2 != b2*b1
print(c)
print(d)
#print(b1.dot(b2)) (another method)

[[1 2 3]
 [3 4 5]]
[[5 6]
 [7 8]
 [1 2]]
[[22 28]
 [48 60]]
[[23 34 45]
 [31 46 61]
 [ 7 10 13]]


In [ ]:
b1 = np.array([[1,2],[3,4]]) #square matrix
b2 = np.array([[5,6],[7,8]])
c = np.cross(b1,b2) #[1*6-5*2  3*8-4*7] (vector multiplication)
d = np.dot(b1,b2)
e = np.dot(b2,b1)
print(c)
print(d)
print(e)

[-4 -4]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [ ]:
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))
print (t1)
print (t2)
t3 = t1 + t2
print(t3)

[[4 5 4]
 [3 5 4]
 [3 3 4]]
[[5 4 5]
 [4 3 5]
 [3 3 4]]
[[9 9 9]
 [7 8 9]
 [6 6 8]]


In [ ]:
#statistical operations
mean = t3.mean()
mode = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)
print(mean)
print(mode)
print(median)
print(std)
print(var)

7.888888888888889
9
8.0
1.1967032904743342
1.432098765432099


In [ ]:
std*std #variance

1.4320987654320987

In [ ]:
#Trignometric func
angles = np.array([0,15,30,45,60,75,90])
#sin(array)
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))
print(result)
print(result1)
print(result/result1) #tan
print(result2)


[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)
#reshape trhe array
reshapearr = arr.reshape(2,3)
reshapearr1 = arr.reshape(6,1)
#convert / Flatten any n dim array
flattendarr = arr.flatten()


print(reshapearr)
print(reshapearr1)
print(flattendarr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [ ]:
#stacking data
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
arr3 = np.vstack((arr1,arr2)) #vertical stack - dimensions have to equal
print(arr3)
print(arr3.shape)
print(np.hstack((arr1,arr2))) #horizontal stack


[[ 1  2  3  4]
 [10 20 30 40]]
(2, 4)
[ 1  2  3  4 10 20 30 40]


In [ ]:
#filtering
arr = np.array([10,20,30,40,50,60,70,80])
farr = arr[arr>40]
print (farr)

[50 60 70 80]
